actions, daily_checks: Fixes and cosmetics (#89)
- Run all checks independently (even if other fail)
- Connect step failure with slack message by checking
  steps.<step_id>.outcome
- Make step names more specific
- Use markdown_text instead of text for Slack messages

Co-authored-by: Stanislav German-Evtushenko <ginermail@gmail.com>

diff --git a/.github/workflows/daily_checks.yml b/.github/workflows/daily_checks.yml
--- a/.github/workflows/daily_checks.yml
+++ b/.github/workflows/daily_checks.yml
@@ -26,6 +26,8 @@ jobs:
         uses: actions/checkout@v4
 
       - name: Check diff for reward weights
+        id: diff-reward-weights
+        if: success() || failure()  # Run this step even if one of the previous steps failed
         run: |
           result=$(scripts/diff-reward-weights.sh) && exit_code=$? || exit_code=$?
           echo "$result"
@@ -38,8 +40,8 @@ jobs:
 
           exit "$exit_code"
 
-      - name: Post text to a Slack channel
-        #if: failure()
+      - name: Post reward weights check results to a Slack channel
+        #if: failure() && steps.diff-reward-weights.outcome == 'failure'
         if: false  # Temporarily disabled until a proper process to handle the diff is established
         uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d  # v2.0.0
         with:
@@ -47,4 +49,4 @@ jobs:
           token: ${{ secrets.SLACK_BOT_TOKEN }}
           payload: |
             channel: ${{ secrets.SLACK_CHANNEL_ID_SUPERVALIDATOR_OPERATIONS }}
-            text: ":warning: One more more configuration checks failed. Please check the <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|logs> for details."
+            markdown_text: ":warning: One more more configuration checks failed. Please check the [logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details."
