actions, daily_checks: Add warning for expiring votes and missing voters (#90)
Message to Slack missing voters for vote requests expiring in less than
one day

Co-authored-by: Stanislav German-Evtushenko <ginermail@gmail.com>

diff --git a/.github/workflows/daily_checks.yml b/.github/workflows/daily_checks.yml
--- a/.github/workflows/daily_checks.yml
+++ b/.github/workflows/daily_checks.yml
@@ -50,3 +50,34 @@ jobs:
           payload: |
             channel: ${{ secrets.SLACK_CHANNEL_ID_SUPERVALIDATOR_OPERATIONS }}
             markdown_text: ":warning: One more more configuration checks failed. Please check the [logs](${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}) for details."
+
+      - name: Get missing voters
+        id: get-missing-voters
+        if: success() || failure()  # Run this step even if one of the previous steps failed
+        run: |
+          result=$(scripts/get-missing-voters.sh 1) && exit_code=$? || exit_code=$?
+          echo "$result"
+
+          {
+            echo '```'
+            echo "$result"
+            echo '```'
+          } >> "$GITHUB_STEP_SUMMARY"
+
+          {
+            echo "slack_message<<EOF"
+            echo ":warning: $result"
+            echo "EOF"
+          } >> "$GITHUB_OUTPUT"
+
+          exit "$exit_code"
+
+      - name: Post missing voters check results to a Slack channel
+        if: failure() && steps.get-missing-voters.outcome == 'failure'
+        uses: slackapi/slack-github-action@485a9d42d3a73031f12ec201c457e2162c45d02d  # v2.0.0
+        with:
+          method: chat.postMessage
+          token: ${{ secrets.SLACK_BOT_TOKEN }}
+          payload: |
+            channel: ${{ secrets.SLACK_CHANNEL_ID_SUPERVALIDATOR_OPERATIONS }}
+            markdown_text: ${{ toJSON(steps.get-missing-voters.outputs.slack_message) }}
